name: hot_desking
description: A new Flutter project.

publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  get: ^4.6.1
  page_transition: ^2.0.4
  flutter_screenutil: ^5.1.0
  persistent_bottom_nav_bar:
    path: packages/persistent_bottom_nav_bar
  qr_code_scanner: ^0.7.0
  shared_preferences: ^2.0.13
  date_picker_timeline: ^1.2.3
  image_picker: ^0.8.4+4
  firebase_storage: ^10.2.9
  firebase_core: ^1.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/desq_logo.png"
  adaptive_icon_background: "#361E55"
  adaptive_icon_foreground: "assets/logo/desq_logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/common/
    - assets/login/
    - assets/welcome_screen/
    - assets/chairs/
    - assets/level3/
    - assets/rooms/